name: wallet
description: EDI - NL Public Reference Wallet

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  equatable: ^2.0.5
  collection: ^1.16.0
  fimber: ^0.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  mobile_scanner: ^2.0.0
  permission_handler: ^10.2.0
  rxdart: ^0.27.5
  flutter_sticky_header: ^0.6.4
  url_launcher: ^6.1.6
  vibration: ^1.7.6
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  arb_utils: ^0.4.1
  qr_flutter: ^4.0.0
  screen_brightness: ^0.2.2
  package_info_plus: ^3.0.2
  nfc_manager: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # Consider migrating to rename package for multi platform support
  change_app_package_name: ^1.1.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/non-free/images/

  fonts:
    - family: RijksoverheidSansWebText
      fonts:
        - asset: assets/non-free/fonts/rijksoverheid-sans-web-text-regular.ttf
          weight: 400
        - asset: assets/non-free/fonts/rijksoverheid-sans-web-text-bold.ttf
          weight: 700
